### ISSUE TITLE
Asks for the passphrase in loops

### ISSUE THREAD

**Issue by 7heo** [7heo/mkinitfs-issues#1]
The current version (this repository) of `nlplug-findfs` keeps asking for the passphrase before failing.

**Comment by 7heo** [comment]
@ncopa Any idea why?

**Comment by ncopa** [comment]
no idea why, but yes this is what i have observed too.

**Comment by 7heo** [comment]
This was caused by the function `start_cryptsetup` being called more than once, since there was no check if the event was for a device already opened or not (since *both* the actions `add` and `change` triggered the call).

So the first time (`add` action), the start_cryptsetup() was doing its job, the second time (`change` action), it was a rogue call.

**Comment by 7heo** [comment]
fixed by https://github.com/7heo/mkinitfs/commit/abdc0f34c6f07baf4c8d2952861747ae82e1fefa too.

**Comment by 7heo** [comment]
This issue was moved to 7heo/mkinitfs#4
