### ISSUE TITLE
Segfaults with header option

### ISSUE THREAD

**Issue by 7heo** [7heo/mkinitfs-issues#2]
This `nlplug-findfs` segfaults with the new header option, at the end of the execution, after asking the passphrase too many times (as reported in #1).

**Comment by ncopa** [comment]
backtrace?

**Comment by 7heo** [comment]
Fixed in https://github.com/7heo/mkinitfs/commit/abdc0f34c6f07baf4c8d2952861747ae82e1fefa

**Comment by 7heo** [comment]
This issue was moved to 7heo/mkinitfs#5
